### ISSUE TITLE
Todo/Ideas issue.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [Legend-of-iPhoenix/Village#1]
This is for putting ideas I have/you have. I'm probably never going to close this issue. A todo list will be curated and put into this issue here. If your idea is accepted, you will find it in the first post.

- [x] Conditionals (`Ask <villager> if <he/she> has <item>.`)
- [ ] Loops (`Until <event>, <do something>.`) (This can already be done using conditionals and skips)
- [x] "Variables" (`Tell villager to write the number of <item>s <he/she> has onto <his/her> scroll.`)
- [ ] More villager names (I'm using the names of famous computer scientists.)
- [x] **Documentation**, in big, red, flaming letters (I tried to do this, but GitHub didn't like my injected HTML)
- [ ] Example code.
- [ ] Internal code documentation.
- [ ] Routines? (almost like functions, but they don't take input? Maybe? I don't know how I can make this fit in.)
 - [x] Jumps (`Skip to step <n>.`)
 - [x] `Tell <villager> to write <his/her> occupation on <his/her> scroll.`
 - [x] `Ask <villager> if <he/she> is a <occupation>.`
 - [x] `Ask <villager> if <he/she> has <more/less> <item> than <other villager>.`
 - [X] Villager limits
 - [x] `Tell <villager> to swap scrolls with <villager>`
 - [X] Ability to specify villager occupation.
 - [ ] Allow changing of max execution time.
 - [ ] Input. Again, no clue how I am going to implement this. (maybe using trains? Perhaps a library or even a *in*nkeeper?)
 - [x] TRAINS! (partial implementation - you can't use them, but they exist and can be built)

**Comment by LAX18** [comment]
Make a Github project todo list. Then things can be so much easier. Or do something like this:  
- [ ] Something
- [ ] Something Else

**Comment by npease18** [comment]
Make a Github project todo list. Then things can be so much easier. Or do something like this:
- [ ] Something
- [ ] Something Else
- [X] Something Done
  

BTW, the code is - [ ] for a undone item and -[X] for a done one'

**Comment by Legend-of-iPhoenix** [comment]
Fancy!

Edit, the edits were me clicking the checkboxes, apparently because I have edit access I can click them and change them.

**Comment by npease18** [comment]
Ah okay. It seems I can as well.

Did not know this as I made it on mobile.

**Comment by Legend-of-iPhoenix** [comment]
You can because you made the post. This is really cool! (Thanks for showing me)

I finished implementing if-statements, which is awesome! I still want to do more in that field though, but that's something for tomorrow.

**Comment by Legend-of-iPhoenix** [comment]
I have an idea:
 - You start out with the ability to call exactly enough villagers to gather materials for and build a house.
 - Once you build said house, you can call for more villagers.
